// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigProduce.proto

package com.inke.conf;

public final class ConfigProduceAll {
  private ConfigProduceAll() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigProduceListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigProduceList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    java.util.List<com.inke.conf.ConfigProduceAll.ConfigProduce> 
        getListList();
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    com.inke.conf.ConfigProduceAll.ConfigProduce getList(int index);
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    java.util.List<? extends com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigProduceList}
   */
  public static final class ConfigProduceList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigProduceList)
      ConfigProduceListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigProduceList.newBuilder() to construct.
    private ConfigProduceList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigProduceList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigProduceList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigProduceList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.inke.conf.ConfigProduceAll.ConfigProduce>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.inke.conf.ConfigProduceAll.ConfigProduce.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduceList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigProduceAll.ConfigProduceList.class, com.inke.conf.ConfigProduceAll.ConfigProduceList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.inke.conf.ConfigProduceAll.ConfigProduce> list_;
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.inke.conf.ConfigProduceAll.ConfigProduce> getListList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigProduceAll.ConfigProduce getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .ConfigProduce list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigProduceAll.ConfigProduceList)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigProduceAll.ConfigProduceList other = (com.inke.conf.ConfigProduceAll.ConfigProduceList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigProduceAll.ConfigProduceList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigProduceList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigProduceList)
        com.inke.conf.ConfigProduceAll.ConfigProduceListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduceList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduceList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigProduceAll.ConfigProduceList.class, com.inke.conf.ConfigProduceAll.ConfigProduceList.Builder.class);
      }

      // Construct using com.inke.conf.ConfigProduceAll.ConfigProduceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduceList_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigProduceAll.ConfigProduceList getDefaultInstanceForType() {
        return com.inke.conf.ConfigProduceAll.ConfigProduceList.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigProduceAll.ConfigProduceList build() {
        com.inke.conf.ConfigProduceAll.ConfigProduceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigProduceAll.ConfigProduceList buildPartial() {
        com.inke.conf.ConfigProduceAll.ConfigProduceList result = new com.inke.conf.ConfigProduceAll.ConfigProduceList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigProduceAll.ConfigProduceList) {
          return mergeFrom((com.inke.conf.ConfigProduceAll.ConfigProduceList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigProduceAll.ConfigProduceList other) {
        if (other == com.inke.conf.ConfigProduceAll.ConfigProduceList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigProduceAll.ConfigProduceList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigProduceAll.ConfigProduceList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.inke.conf.ConfigProduceAll.ConfigProduce> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.inke.conf.ConfigProduceAll.ConfigProduce>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigProduceAll.ConfigProduce, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder, com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder> listBuilder_;

      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigProduceAll.ConfigProduce> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public com.inke.conf.ConfigProduceAll.ConfigProduce getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigProduceAll.ConfigProduce value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder addList(com.inke.conf.ConfigProduceAll.ConfigProduce value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigProduceAll.ConfigProduce value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder addList(
          com.inke.conf.ConfigProduceAll.ConfigProduce.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.inke.conf.ConfigProduceAll.ConfigProduce> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public com.inke.conf.ConfigProduceAll.ConfigProduce.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public java.util.List<? extends com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public com.inke.conf.ConfigProduceAll.ConfigProduce.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.inke.conf.ConfigProduceAll.ConfigProduce.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public com.inke.conf.ConfigProduceAll.ConfigProduce.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.inke.conf.ConfigProduceAll.ConfigProduce.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigProduce list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigProduceAll.ConfigProduce.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigProduceAll.ConfigProduce, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder, com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.inke.conf.ConfigProduceAll.ConfigProduce, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder, com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigProduceList)
    }

    // @@protoc_insertion_point(class_scope:ConfigProduceList)
    private static final com.inke.conf.ConfigProduceAll.ConfigProduceList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigProduceAll.ConfigProduceList();
    }

    public static com.inke.conf.ConfigProduceAll.ConfigProduceList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigProduceList>
        PARSER = new com.google.protobuf.AbstractParser<ConfigProduceList>() {
      @java.lang.Override
      public ConfigProduceList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigProduceList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigProduceList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigProduceList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigProduceAll.ConfigProduceList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigProduceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigProduce)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 maxStorageAmount = 2;</code>
     * @return The maxStorageAmount.
     */
    int getMaxStorageAmount();

    /**
     * <code>int32 produceGoldAmount = 3;</code>
     * @return The produceGoldAmount.
     */
    int getProduceGoldAmount();

    /**
     * <code>int32 produceGoldInterval = 4;</code>
     * @return The produceGoldInterval.
     */
    int getProduceGoldInterval();

    /**
     * <code>int32 goldGainRate = 5;</code>
     * @return The goldGainRate.
     */
    int getGoldGainRate();

    /**
     * <code>int32 produceShockAmount = 6;</code>
     * @return The produceShockAmount.
     */
    int getProduceShockAmount();

    /**
     * <code>int32 produceShockInterval = 7;</code>
     * @return The produceShockInterval.
     */
    int getProduceShockInterval();
  }
  /**
   * Protobuf type {@code ConfigProduce}
   */
  public static final class ConfigProduce extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigProduce)
      ConfigProduceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigProduce.newBuilder() to construct.
    private ConfigProduce(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigProduce() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigProduce();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigProduce(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              maxStorageAmount_ = input.readInt32();
              break;
            }
            case 24: {

              produceGoldAmount_ = input.readInt32();
              break;
            }
            case 32: {

              produceGoldInterval_ = input.readInt32();
              break;
            }
            case 40: {

              goldGainRate_ = input.readInt32();
              break;
            }
            case 48: {

              produceShockAmount_ = input.readInt32();
              break;
            }
            case 56: {

              produceShockInterval_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduce_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduce_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigProduceAll.ConfigProduce.class, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int MAXSTORAGEAMOUNT_FIELD_NUMBER = 2;
    private int maxStorageAmount_;
    /**
     * <code>int32 maxStorageAmount = 2;</code>
     * @return The maxStorageAmount.
     */
    @java.lang.Override
    public int getMaxStorageAmount() {
      return maxStorageAmount_;
    }

    public static final int PRODUCEGOLDAMOUNT_FIELD_NUMBER = 3;
    private int produceGoldAmount_;
    /**
     * <code>int32 produceGoldAmount = 3;</code>
     * @return The produceGoldAmount.
     */
    @java.lang.Override
    public int getProduceGoldAmount() {
      return produceGoldAmount_;
    }

    public static final int PRODUCEGOLDINTERVAL_FIELD_NUMBER = 4;
    private int produceGoldInterval_;
    /**
     * <code>int32 produceGoldInterval = 4;</code>
     * @return The produceGoldInterval.
     */
    @java.lang.Override
    public int getProduceGoldInterval() {
      return produceGoldInterval_;
    }

    public static final int GOLDGAINRATE_FIELD_NUMBER = 5;
    private int goldGainRate_;
    /**
     * <code>int32 goldGainRate = 5;</code>
     * @return The goldGainRate.
     */
    @java.lang.Override
    public int getGoldGainRate() {
      return goldGainRate_;
    }

    public static final int PRODUCESHOCKAMOUNT_FIELD_NUMBER = 6;
    private int produceShockAmount_;
    /**
     * <code>int32 produceShockAmount = 6;</code>
     * @return The produceShockAmount.
     */
    @java.lang.Override
    public int getProduceShockAmount() {
      return produceShockAmount_;
    }

    public static final int PRODUCESHOCKINTERVAL_FIELD_NUMBER = 7;
    private int produceShockInterval_;
    /**
     * <code>int32 produceShockInterval = 7;</code>
     * @return The produceShockInterval.
     */
    @java.lang.Override
    public int getProduceShockInterval() {
      return produceShockInterval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (maxStorageAmount_ != 0) {
        output.writeInt32(2, maxStorageAmount_);
      }
      if (produceGoldAmount_ != 0) {
        output.writeInt32(3, produceGoldAmount_);
      }
      if (produceGoldInterval_ != 0) {
        output.writeInt32(4, produceGoldInterval_);
      }
      if (goldGainRate_ != 0) {
        output.writeInt32(5, goldGainRate_);
      }
      if (produceShockAmount_ != 0) {
        output.writeInt32(6, produceShockAmount_);
      }
      if (produceShockInterval_ != 0) {
        output.writeInt32(7, produceShockInterval_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (maxStorageAmount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxStorageAmount_);
      }
      if (produceGoldAmount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, produceGoldAmount_);
      }
      if (produceGoldInterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, produceGoldInterval_);
      }
      if (goldGainRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, goldGainRate_);
      }
      if (produceShockAmount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, produceShockAmount_);
      }
      if (produceShockInterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, produceShockInterval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigProduceAll.ConfigProduce)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigProduceAll.ConfigProduce other = (com.inke.conf.ConfigProduceAll.ConfigProduce) obj;

      if (getId()
          != other.getId()) return false;
      if (getMaxStorageAmount()
          != other.getMaxStorageAmount()) return false;
      if (getProduceGoldAmount()
          != other.getProduceGoldAmount()) return false;
      if (getProduceGoldInterval()
          != other.getProduceGoldInterval()) return false;
      if (getGoldGainRate()
          != other.getGoldGainRate()) return false;
      if (getProduceShockAmount()
          != other.getProduceShockAmount()) return false;
      if (getProduceShockInterval()
          != other.getProduceShockInterval()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + MAXSTORAGEAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getMaxStorageAmount();
      hash = (37 * hash) + PRODUCEGOLDAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getProduceGoldAmount();
      hash = (37 * hash) + PRODUCEGOLDINTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getProduceGoldInterval();
      hash = (37 * hash) + GOLDGAINRATE_FIELD_NUMBER;
      hash = (53 * hash) + getGoldGainRate();
      hash = (37 * hash) + PRODUCESHOCKAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getProduceShockAmount();
      hash = (37 * hash) + PRODUCESHOCKINTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getProduceShockInterval();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigProduceAll.ConfigProduce parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigProduceAll.ConfigProduce prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigProduce}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigProduce)
        com.inke.conf.ConfigProduceAll.ConfigProduceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduce_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduce_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigProduceAll.ConfigProduce.class, com.inke.conf.ConfigProduceAll.ConfigProduce.Builder.class);
      }

      // Construct using com.inke.conf.ConfigProduceAll.ConfigProduce.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        maxStorageAmount_ = 0;

        produceGoldAmount_ = 0;

        produceGoldInterval_ = 0;

        goldGainRate_ = 0;

        produceShockAmount_ = 0;

        produceShockInterval_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigProduceAll.internal_static_ConfigProduce_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigProduceAll.ConfigProduce getDefaultInstanceForType() {
        return com.inke.conf.ConfigProduceAll.ConfigProduce.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigProduceAll.ConfigProduce build() {
        com.inke.conf.ConfigProduceAll.ConfigProduce result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigProduceAll.ConfigProduce buildPartial() {
        com.inke.conf.ConfigProduceAll.ConfigProduce result = new com.inke.conf.ConfigProduceAll.ConfigProduce(this);
        result.id_ = id_;
        result.maxStorageAmount_ = maxStorageAmount_;
        result.produceGoldAmount_ = produceGoldAmount_;
        result.produceGoldInterval_ = produceGoldInterval_;
        result.goldGainRate_ = goldGainRate_;
        result.produceShockAmount_ = produceShockAmount_;
        result.produceShockInterval_ = produceShockInterval_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigProduceAll.ConfigProduce) {
          return mergeFrom((com.inke.conf.ConfigProduceAll.ConfigProduce)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigProduceAll.ConfigProduce other) {
        if (other == com.inke.conf.ConfigProduceAll.ConfigProduce.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getMaxStorageAmount() != 0) {
          setMaxStorageAmount(other.getMaxStorageAmount());
        }
        if (other.getProduceGoldAmount() != 0) {
          setProduceGoldAmount(other.getProduceGoldAmount());
        }
        if (other.getProduceGoldInterval() != 0) {
          setProduceGoldInterval(other.getProduceGoldInterval());
        }
        if (other.getGoldGainRate() != 0) {
          setGoldGainRate(other.getGoldGainRate());
        }
        if (other.getProduceShockAmount() != 0) {
          setProduceShockAmount(other.getProduceShockAmount());
        }
        if (other.getProduceShockInterval() != 0) {
          setProduceShockInterval(other.getProduceShockInterval());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigProduceAll.ConfigProduce parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigProduceAll.ConfigProduce) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int maxStorageAmount_ ;
      /**
       * <code>int32 maxStorageAmount = 2;</code>
       * @return The maxStorageAmount.
       */
      @java.lang.Override
      public int getMaxStorageAmount() {
        return maxStorageAmount_;
      }
      /**
       * <code>int32 maxStorageAmount = 2;</code>
       * @param value The maxStorageAmount to set.
       * @return This builder for chaining.
       */
      public Builder setMaxStorageAmount(int value) {
        
        maxStorageAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 maxStorageAmount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxStorageAmount() {
        
        maxStorageAmount_ = 0;
        onChanged();
        return this;
      }

      private int produceGoldAmount_ ;
      /**
       * <code>int32 produceGoldAmount = 3;</code>
       * @return The produceGoldAmount.
       */
      @java.lang.Override
      public int getProduceGoldAmount() {
        return produceGoldAmount_;
      }
      /**
       * <code>int32 produceGoldAmount = 3;</code>
       * @param value The produceGoldAmount to set.
       * @return This builder for chaining.
       */
      public Builder setProduceGoldAmount(int value) {
        
        produceGoldAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 produceGoldAmount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduceGoldAmount() {
        
        produceGoldAmount_ = 0;
        onChanged();
        return this;
      }

      private int produceGoldInterval_ ;
      /**
       * <code>int32 produceGoldInterval = 4;</code>
       * @return The produceGoldInterval.
       */
      @java.lang.Override
      public int getProduceGoldInterval() {
        return produceGoldInterval_;
      }
      /**
       * <code>int32 produceGoldInterval = 4;</code>
       * @param value The produceGoldInterval to set.
       * @return This builder for chaining.
       */
      public Builder setProduceGoldInterval(int value) {
        
        produceGoldInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 produceGoldInterval = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduceGoldInterval() {
        
        produceGoldInterval_ = 0;
        onChanged();
        return this;
      }

      private int goldGainRate_ ;
      /**
       * <code>int32 goldGainRate = 5;</code>
       * @return The goldGainRate.
       */
      @java.lang.Override
      public int getGoldGainRate() {
        return goldGainRate_;
      }
      /**
       * <code>int32 goldGainRate = 5;</code>
       * @param value The goldGainRate to set.
       * @return This builder for chaining.
       */
      public Builder setGoldGainRate(int value) {
        
        goldGainRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 goldGainRate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGoldGainRate() {
        
        goldGainRate_ = 0;
        onChanged();
        return this;
      }

      private int produceShockAmount_ ;
      /**
       * <code>int32 produceShockAmount = 6;</code>
       * @return The produceShockAmount.
       */
      @java.lang.Override
      public int getProduceShockAmount() {
        return produceShockAmount_;
      }
      /**
       * <code>int32 produceShockAmount = 6;</code>
       * @param value The produceShockAmount to set.
       * @return This builder for chaining.
       */
      public Builder setProduceShockAmount(int value) {
        
        produceShockAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 produceShockAmount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduceShockAmount() {
        
        produceShockAmount_ = 0;
        onChanged();
        return this;
      }

      private int produceShockInterval_ ;
      /**
       * <code>int32 produceShockInterval = 7;</code>
       * @return The produceShockInterval.
       */
      @java.lang.Override
      public int getProduceShockInterval() {
        return produceShockInterval_;
      }
      /**
       * <code>int32 produceShockInterval = 7;</code>
       * @param value The produceShockInterval to set.
       * @return This builder for chaining.
       */
      public Builder setProduceShockInterval(int value) {
        
        produceShockInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 produceShockInterval = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduceShockInterval() {
        
        produceShockInterval_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigProduce)
    }

    // @@protoc_insertion_point(class_scope:ConfigProduce)
    private static final com.inke.conf.ConfigProduceAll.ConfigProduce DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigProduceAll.ConfigProduce();
    }

    public static com.inke.conf.ConfigProduceAll.ConfigProduce getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigProduce>
        PARSER = new com.google.protobuf.AbstractParser<ConfigProduce>() {
      @java.lang.Override
      public ConfigProduce parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigProduce(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigProduce> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigProduce> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigProduceAll.ConfigProduce getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigProduceList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigProduceList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigProduce_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigProduce_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ConfigProduce.proto\"1\n\021ConfigProduceLi" +
      "st\022\034\n\004list\030\001 \003(\0132\016.ConfigProduce\"\275\001\n\rCon" +
      "figProduce\022\n\n\002id\030\001 \001(\005\022\030\n\020maxStorageAmou" +
      "nt\030\002 \001(\005\022\031\n\021produceGoldAmount\030\003 \001(\005\022\033\n\023p" +
      "roduceGoldInterval\030\004 \001(\005\022\024\n\014goldGainRate" +
      "\030\005 \001(\005\022\032\n\022produceShockAmount\030\006 \001(\005\022\034\n\024pr" +
      "oduceShockInterval\030\007 \001(\005B)\n\rcom.inke.con" +
      "fB\020ConfigProduceAllZ\006.;gameb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConfigProduceList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigProduceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigProduceList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ConfigProduce_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigProduce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigProduce_descriptor,
        new java.lang.String[] { "Id", "MaxStorageAmount", "ProduceGoldAmount", "ProduceGoldInterval", "GoldGainRate", "ProduceShockAmount", "ProduceShockInterval", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
