// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigBuilding.proto

package com.inke.conf;

public final class ConfigBuildingAll {
  private ConfigBuildingAll() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigBuildingListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigBuildingList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    java.util.List<com.inke.conf.ConfigBuildingAll.ConfigBuilding> 
        getListList();
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    com.inke.conf.ConfigBuildingAll.ConfigBuilding getList(int index);
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    java.util.List<? extends com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigBuildingList}
   */
  public static final class ConfigBuildingList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigBuildingList)
      ConfigBuildingListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigBuildingList.newBuilder() to construct.
    private ConfigBuildingList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigBuildingList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigBuildingList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigBuildingList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.inke.conf.ConfigBuildingAll.ConfigBuilding>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.inke.conf.ConfigBuildingAll.ConfigBuilding.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuildingList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuildingList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigBuildingAll.ConfigBuildingList.class, com.inke.conf.ConfigBuildingAll.ConfigBuildingList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.inke.conf.ConfigBuildingAll.ConfigBuilding> list_;
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.inke.conf.ConfigBuildingAll.ConfigBuilding> getListList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigBuildingAll.ConfigBuilding getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .ConfigBuilding list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigBuildingAll.ConfigBuildingList)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigBuildingAll.ConfigBuildingList other = (com.inke.conf.ConfigBuildingAll.ConfigBuildingList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigBuildingAll.ConfigBuildingList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigBuildingList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigBuildingList)
        com.inke.conf.ConfigBuildingAll.ConfigBuildingListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuildingList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuildingList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigBuildingAll.ConfigBuildingList.class, com.inke.conf.ConfigBuildingAll.ConfigBuildingList.Builder.class);
      }

      // Construct using com.inke.conf.ConfigBuildingAll.ConfigBuildingList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuildingList_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuildingAll.ConfigBuildingList getDefaultInstanceForType() {
        return com.inke.conf.ConfigBuildingAll.ConfigBuildingList.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuildingAll.ConfigBuildingList build() {
        com.inke.conf.ConfigBuildingAll.ConfigBuildingList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuildingAll.ConfigBuildingList buildPartial() {
        com.inke.conf.ConfigBuildingAll.ConfigBuildingList result = new com.inke.conf.ConfigBuildingAll.ConfigBuildingList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigBuildingAll.ConfigBuildingList) {
          return mergeFrom((com.inke.conf.ConfigBuildingAll.ConfigBuildingList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigBuildingAll.ConfigBuildingList other) {
        if (other == com.inke.conf.ConfigBuildingAll.ConfigBuildingList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigBuildingAll.ConfigBuildingList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigBuildingAll.ConfigBuildingList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.inke.conf.ConfigBuildingAll.ConfigBuilding> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.inke.conf.ConfigBuildingAll.ConfigBuilding>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigBuildingAll.ConfigBuilding, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder, com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder> listBuilder_;

      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigBuildingAll.ConfigBuilding> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigBuildingAll.ConfigBuilding value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder addList(com.inke.conf.ConfigBuildingAll.ConfigBuilding value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigBuildingAll.ConfigBuilding value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder addList(
          com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.inke.conf.ConfigBuildingAll.ConfigBuilding> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public java.util.List<? extends com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.inke.conf.ConfigBuildingAll.ConfigBuilding.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.inke.conf.ConfigBuildingAll.ConfigBuilding.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigBuilding list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigBuildingAll.ConfigBuilding, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder, com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.inke.conf.ConfigBuildingAll.ConfigBuilding, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder, com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigBuildingList)
    }

    // @@protoc_insertion_point(class_scope:ConfigBuildingList)
    private static final com.inke.conf.ConfigBuildingAll.ConfigBuildingList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigBuildingAll.ConfigBuildingList();
    }

    public static com.inke.conf.ConfigBuildingAll.ConfigBuildingList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigBuildingList>
        PARSER = new com.google.protobuf.AbstractParser<ConfigBuildingList>() {
      @java.lang.Override
      public ConfigBuildingList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigBuildingList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigBuildingList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigBuildingList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigBuildingAll.ConfigBuildingList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigBuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigBuilding)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 typeId = 1;</code>
     * @return The typeId.
     */
    int getTypeId();

    /**
     * <code>int32 level = 2;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>int32 uniqueId = 3;</code>
     * @return The uniqueId.
     */
    int getUniqueId();

    /**
     * <code>int32 miniMapId = 4;</code>
     * @return The miniMapId.
     */
    int getMiniMapId();

    /**
     * <code>int32 produceId = 5;</code>
     * @return The produceId.
     */
    int getProduceId();

    /**
     * <code>int32 priceId = 6;</code>
     * @return The priceId.
     */
    int getPriceId();

    /**
     * <code>int32 descId = 7;</code>
     * @return The descId.
     */
    int getDescId();
  }
  /**
   * Protobuf type {@code ConfigBuilding}
   */
  public static final class ConfigBuilding extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigBuilding)
      ConfigBuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigBuilding.newBuilder() to construct.
    private ConfigBuilding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigBuilding() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigBuilding();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigBuilding(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              typeId_ = input.readInt32();
              break;
            }
            case 16: {

              level_ = input.readInt32();
              break;
            }
            case 24: {

              uniqueId_ = input.readInt32();
              break;
            }
            case 32: {

              miniMapId_ = input.readInt32();
              break;
            }
            case 40: {

              produceId_ = input.readInt32();
              break;
            }
            case 48: {

              priceId_ = input.readInt32();
              break;
            }
            case 56: {

              descId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuilding_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuilding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigBuildingAll.ConfigBuilding.class, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder.class);
    }

    public static final int TYPEID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <code>int32 typeId = 1;</code>
     * @return The typeId.
     */
    @java.lang.Override
    public int getTypeId() {
      return typeId_;
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>int32 level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }

    public static final int UNIQUEID_FIELD_NUMBER = 3;
    private int uniqueId_;
    /**
     * <code>int32 uniqueId = 3;</code>
     * @return The uniqueId.
     */
    @java.lang.Override
    public int getUniqueId() {
      return uniqueId_;
    }

    public static final int MINIMAPID_FIELD_NUMBER = 4;
    private int miniMapId_;
    /**
     * <code>int32 miniMapId = 4;</code>
     * @return The miniMapId.
     */
    @java.lang.Override
    public int getMiniMapId() {
      return miniMapId_;
    }

    public static final int PRODUCEID_FIELD_NUMBER = 5;
    private int produceId_;
    /**
     * <code>int32 produceId = 5;</code>
     * @return The produceId.
     */
    @java.lang.Override
    public int getProduceId() {
      return produceId_;
    }

    public static final int PRICEID_FIELD_NUMBER = 6;
    private int priceId_;
    /**
     * <code>int32 priceId = 6;</code>
     * @return The priceId.
     */
    @java.lang.Override
    public int getPriceId() {
      return priceId_;
    }

    public static final int DESCID_FIELD_NUMBER = 7;
    private int descId_;
    /**
     * <code>int32 descId = 7;</code>
     * @return The descId.
     */
    @java.lang.Override
    public int getDescId() {
      return descId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeId_ != 0) {
        output.writeInt32(1, typeId_);
      }
      if (level_ != 0) {
        output.writeInt32(2, level_);
      }
      if (uniqueId_ != 0) {
        output.writeInt32(3, uniqueId_);
      }
      if (miniMapId_ != 0) {
        output.writeInt32(4, miniMapId_);
      }
      if (produceId_ != 0) {
        output.writeInt32(5, produceId_);
      }
      if (priceId_ != 0) {
        output.writeInt32(6, priceId_);
      }
      if (descId_ != 0) {
        output.writeInt32(7, descId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, typeId_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      if (uniqueId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, uniqueId_);
      }
      if (miniMapId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, miniMapId_);
      }
      if (produceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, produceId_);
      }
      if (priceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, priceId_);
      }
      if (descId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, descId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigBuildingAll.ConfigBuilding)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigBuildingAll.ConfigBuilding other = (com.inke.conf.ConfigBuildingAll.ConfigBuilding) obj;

      if (getTypeId()
          != other.getTypeId()) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (getUniqueId()
          != other.getUniqueId()) return false;
      if (getMiniMapId()
          != other.getMiniMapId()) return false;
      if (getProduceId()
          != other.getProduceId()) return false;
      if (getPriceId()
          != other.getPriceId()) return false;
      if (getDescId()
          != other.getDescId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + UNIQUEID_FIELD_NUMBER;
      hash = (53 * hash) + getUniqueId();
      hash = (37 * hash) + MINIMAPID_FIELD_NUMBER;
      hash = (53 * hash) + getMiniMapId();
      hash = (37 * hash) + PRODUCEID_FIELD_NUMBER;
      hash = (53 * hash) + getProduceId();
      hash = (37 * hash) + PRICEID_FIELD_NUMBER;
      hash = (53 * hash) + getPriceId();
      hash = (37 * hash) + DESCID_FIELD_NUMBER;
      hash = (53 * hash) + getDescId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigBuildingAll.ConfigBuilding prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigBuilding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigBuilding)
        com.inke.conf.ConfigBuildingAll.ConfigBuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuilding_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuilding_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigBuildingAll.ConfigBuilding.class, com.inke.conf.ConfigBuildingAll.ConfigBuilding.Builder.class);
      }

      // Construct using com.inke.conf.ConfigBuildingAll.ConfigBuilding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeId_ = 0;

        level_ = 0;

        uniqueId_ = 0;

        miniMapId_ = 0;

        produceId_ = 0;

        priceId_ = 0;

        descId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigBuildingAll.internal_static_ConfigBuilding_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding getDefaultInstanceForType() {
        return com.inke.conf.ConfigBuildingAll.ConfigBuilding.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding build() {
        com.inke.conf.ConfigBuildingAll.ConfigBuilding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuildingAll.ConfigBuilding buildPartial() {
        com.inke.conf.ConfigBuildingAll.ConfigBuilding result = new com.inke.conf.ConfigBuildingAll.ConfigBuilding(this);
        result.typeId_ = typeId_;
        result.level_ = level_;
        result.uniqueId_ = uniqueId_;
        result.miniMapId_ = miniMapId_;
        result.produceId_ = produceId_;
        result.priceId_ = priceId_;
        result.descId_ = descId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigBuildingAll.ConfigBuilding) {
          return mergeFrom((com.inke.conf.ConfigBuildingAll.ConfigBuilding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigBuildingAll.ConfigBuilding other) {
        if (other == com.inke.conf.ConfigBuildingAll.ConfigBuilding.getDefaultInstance()) return this;
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getUniqueId() != 0) {
          setUniqueId(other.getUniqueId());
        }
        if (other.getMiniMapId() != 0) {
          setMiniMapId(other.getMiniMapId());
        }
        if (other.getProduceId() != 0) {
          setProduceId(other.getProduceId());
        }
        if (other.getPriceId() != 0) {
          setPriceId(other.getPriceId());
        }
        if (other.getDescId() != 0) {
          setDescId(other.getDescId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigBuildingAll.ConfigBuilding parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigBuildingAll.ConfigBuilding) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int typeId_ ;
      /**
       * <code>int32 typeId = 1;</code>
       * @return The typeId.
       */
      @java.lang.Override
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>int32 typeId = 1;</code>
       * @param value The typeId to set.
       * @return This builder for chaining.
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 2;</code>
       * @return The level.
       */
      @java.lang.Override
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 2;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int uniqueId_ ;
      /**
       * <code>int32 uniqueId = 3;</code>
       * @return The uniqueId.
       */
      @java.lang.Override
      public int getUniqueId() {
        return uniqueId_;
      }
      /**
       * <code>int32 uniqueId = 3;</code>
       * @param value The uniqueId to set.
       * @return This builder for chaining.
       */
      public Builder setUniqueId(int value) {
        
        uniqueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uniqueId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUniqueId() {
        
        uniqueId_ = 0;
        onChanged();
        return this;
      }

      private int miniMapId_ ;
      /**
       * <code>int32 miniMapId = 4;</code>
       * @return The miniMapId.
       */
      @java.lang.Override
      public int getMiniMapId() {
        return miniMapId_;
      }
      /**
       * <code>int32 miniMapId = 4;</code>
       * @param value The miniMapId to set.
       * @return This builder for chaining.
       */
      public Builder setMiniMapId(int value) {
        
        miniMapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 miniMapId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMiniMapId() {
        
        miniMapId_ = 0;
        onChanged();
        return this;
      }

      private int produceId_ ;
      /**
       * <code>int32 produceId = 5;</code>
       * @return The produceId.
       */
      @java.lang.Override
      public int getProduceId() {
        return produceId_;
      }
      /**
       * <code>int32 produceId = 5;</code>
       * @param value The produceId to set.
       * @return This builder for chaining.
       */
      public Builder setProduceId(int value) {
        
        produceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 produceId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduceId() {
        
        produceId_ = 0;
        onChanged();
        return this;
      }

      private int priceId_ ;
      /**
       * <code>int32 priceId = 6;</code>
       * @return The priceId.
       */
      @java.lang.Override
      public int getPriceId() {
        return priceId_;
      }
      /**
       * <code>int32 priceId = 6;</code>
       * @param value The priceId to set.
       * @return This builder for chaining.
       */
      public Builder setPriceId(int value) {
        
        priceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 priceId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceId() {
        
        priceId_ = 0;
        onChanged();
        return this;
      }

      private int descId_ ;
      /**
       * <code>int32 descId = 7;</code>
       * @return The descId.
       */
      @java.lang.Override
      public int getDescId() {
        return descId_;
      }
      /**
       * <code>int32 descId = 7;</code>
       * @param value The descId to set.
       * @return This builder for chaining.
       */
      public Builder setDescId(int value) {
        
        descId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 descId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescId() {
        
        descId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigBuilding)
    }

    // @@protoc_insertion_point(class_scope:ConfigBuilding)
    private static final com.inke.conf.ConfigBuildingAll.ConfigBuilding DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigBuildingAll.ConfigBuilding();
    }

    public static com.inke.conf.ConfigBuildingAll.ConfigBuilding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigBuilding>
        PARSER = new com.google.protobuf.AbstractParser<ConfigBuilding>() {
      @java.lang.Override
      public ConfigBuilding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigBuilding(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigBuilding> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigBuilding> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigBuildingAll.ConfigBuilding getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigBuildingList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigBuildingList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigBuilding_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigBuilding_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ConfigBuilding.proto\"3\n\022ConfigBuilding" +
      "List\022\035\n\004list\030\001 \003(\0132\017.ConfigBuilding\"\210\001\n\016" +
      "ConfigBuilding\022\016\n\006typeId\030\001 \001(\005\022\r\n\005level\030" +
      "\002 \001(\005\022\020\n\010uniqueId\030\003 \001(\005\022\021\n\tminiMapId\030\004 \001" +
      "(\005\022\021\n\tproduceId\030\005 \001(\005\022\017\n\007priceId\030\006 \001(\005\022\016" +
      "\n\006descId\030\007 \001(\005B*\n\rcom.inke.confB\021ConfigB" +
      "uildingAllZ\006.;gameb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConfigBuildingList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigBuildingList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigBuildingList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ConfigBuilding_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigBuilding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigBuilding_descriptor,
        new java.lang.String[] { "TypeId", "Level", "UniqueId", "MiniMapId", "ProduceId", "PriceId", "DescId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
