// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigDesc.proto

package com.inke.conf;

public final class ConfigDescAll {
  private ConfigDescAll() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigDescListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigDescList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    java.util.List<com.inke.conf.ConfigDescAll.ConfigDesc> 
        getListList();
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    com.inke.conf.ConfigDescAll.ConfigDesc getList(int index);
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    java.util.List<? extends com.inke.conf.ConfigDescAll.ConfigDescOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    com.inke.conf.ConfigDescAll.ConfigDescOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigDescList}
   */
  public static final class ConfigDescList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigDescList)
      ConfigDescListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigDescList.newBuilder() to construct.
    private ConfigDescList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigDescList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigDescList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigDescList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.inke.conf.ConfigDescAll.ConfigDesc>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.inke.conf.ConfigDescAll.ConfigDesc.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigDescAll.internal_static_ConfigDescList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigDescAll.internal_static_ConfigDescList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigDescAll.ConfigDescList.class, com.inke.conf.ConfigDescAll.ConfigDescList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.inke.conf.ConfigDescAll.ConfigDesc> list_;
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.inke.conf.ConfigDescAll.ConfigDesc> getListList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.inke.conf.ConfigDescAll.ConfigDescOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigDescAll.ConfigDesc getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .ConfigDesc list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigDescAll.ConfigDescOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigDescAll.ConfigDescList)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigDescAll.ConfigDescList other = (com.inke.conf.ConfigDescAll.ConfigDescList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDescList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigDescAll.ConfigDescList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigDescList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigDescList)
        com.inke.conf.ConfigDescAll.ConfigDescListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigDescAll.internal_static_ConfigDescList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigDescAll.internal_static_ConfigDescList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigDescAll.ConfigDescList.class, com.inke.conf.ConfigDescAll.ConfigDescList.Builder.class);
      }

      // Construct using com.inke.conf.ConfigDescAll.ConfigDescList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigDescAll.internal_static_ConfigDescList_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDescAll.ConfigDescList getDefaultInstanceForType() {
        return com.inke.conf.ConfigDescAll.ConfigDescList.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigDescAll.ConfigDescList build() {
        com.inke.conf.ConfigDescAll.ConfigDescList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDescAll.ConfigDescList buildPartial() {
        com.inke.conf.ConfigDescAll.ConfigDescList result = new com.inke.conf.ConfigDescAll.ConfigDescList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigDescAll.ConfigDescList) {
          return mergeFrom((com.inke.conf.ConfigDescAll.ConfigDescList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigDescAll.ConfigDescList other) {
        if (other == com.inke.conf.ConfigDescAll.ConfigDescList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigDescAll.ConfigDescList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigDescAll.ConfigDescList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.inke.conf.ConfigDescAll.ConfigDesc> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.inke.conf.ConfigDescAll.ConfigDesc>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigDescAll.ConfigDesc, com.inke.conf.ConfigDescAll.ConfigDesc.Builder, com.inke.conf.ConfigDescAll.ConfigDescOrBuilder> listBuilder_;

      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigDescAll.ConfigDesc> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public com.inke.conf.ConfigDescAll.ConfigDesc getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigDescAll.ConfigDesc value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigDescAll.ConfigDesc.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder addList(com.inke.conf.ConfigDescAll.ConfigDesc value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigDescAll.ConfigDesc value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder addList(
          com.inke.conf.ConfigDescAll.ConfigDesc.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigDescAll.ConfigDesc.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.inke.conf.ConfigDescAll.ConfigDesc> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public com.inke.conf.ConfigDescAll.ConfigDesc.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public com.inke.conf.ConfigDescAll.ConfigDescOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public java.util.List<? extends com.inke.conf.ConfigDescAll.ConfigDescOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public com.inke.conf.ConfigDescAll.ConfigDesc.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.inke.conf.ConfigDescAll.ConfigDesc.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public com.inke.conf.ConfigDescAll.ConfigDesc.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.inke.conf.ConfigDescAll.ConfigDesc.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigDesc list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigDescAll.ConfigDesc.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigDescAll.ConfigDesc, com.inke.conf.ConfigDescAll.ConfigDesc.Builder, com.inke.conf.ConfigDescAll.ConfigDescOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.inke.conf.ConfigDescAll.ConfigDesc, com.inke.conf.ConfigDescAll.ConfigDesc.Builder, com.inke.conf.ConfigDescAll.ConfigDescOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigDescList)
    }

    // @@protoc_insertion_point(class_scope:ConfigDescList)
    private static final com.inke.conf.ConfigDescAll.ConfigDescList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigDescAll.ConfigDescList();
    }

    public static com.inke.conf.ConfigDescAll.ConfigDescList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigDescList>
        PARSER = new com.google.protobuf.AbstractParser<ConfigDescList>() {
      @java.lang.Override
      public ConfigDescList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigDescList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigDescList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigDescList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigDescAll.ConfigDescList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigDescOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigDesc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string iconPath = 4;</code>
     * @return The iconPath.
     */
    java.lang.String getIconPath();
    /**
     * <code>string iconPath = 4;</code>
     * @return The bytes for iconPath.
     */
    com.google.protobuf.ByteString
        getIconPathBytes();

    /**
     * <code>string prefabPath = 5;</code>
     * @return The prefabPath.
     */
    java.lang.String getPrefabPath();
    /**
     * <code>string prefabPath = 5;</code>
     * @return The bytes for prefabPath.
     */
    com.google.protobuf.ByteString
        getPrefabPathBytes();
  }
  /**
   * Protobuf type {@code ConfigDesc}
   */
  public static final class ConfigDesc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigDesc)
      ConfigDescOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigDesc.newBuilder() to construct.
    private ConfigDesc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigDesc() {
      desc_ = "";
      name_ = "";
      iconPath_ = "";
      prefabPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigDesc();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigDesc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              iconPath_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              prefabPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigDescAll.internal_static_ConfigDesc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigDescAll.internal_static_ConfigDesc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigDescAll.ConfigDesc.class, com.inke.conf.ConfigDescAll.ConfigDesc.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @java.lang.Override
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICONPATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object iconPath_;
    /**
     * <code>string iconPath = 4;</code>
     * @return The iconPath.
     */
    @java.lang.Override
    public java.lang.String getIconPath() {
      java.lang.Object ref = iconPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconPath_ = s;
        return s;
      }
    }
    /**
     * <code>string iconPath = 4;</code>
     * @return The bytes for iconPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIconPathBytes() {
      java.lang.Object ref = iconPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREFABPATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object prefabPath_;
    /**
     * <code>string prefabPath = 5;</code>
     * @return The prefabPath.
     */
    @java.lang.Override
    public java.lang.String getPrefabPath() {
      java.lang.Object ref = prefabPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prefabPath_ = s;
        return s;
      }
    }
    /**
     * <code>string prefabPath = 5;</code>
     * @return The bytes for prefabPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrefabPathBytes() {
      java.lang.Object ref = prefabPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prefabPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getIconPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, iconPath_);
      }
      if (!getPrefabPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, prefabPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getIconPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, iconPath_);
      }
      if (!getPrefabPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, prefabPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigDescAll.ConfigDesc)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigDescAll.ConfigDesc other = (com.inke.conf.ConfigDescAll.ConfigDesc) obj;

      if (getId()
          != other.getId()) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getIconPath()
          .equals(other.getIconPath())) return false;
      if (!getPrefabPath()
          .equals(other.getPrefabPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ICONPATH_FIELD_NUMBER;
      hash = (53 * hash) + getIconPath().hashCode();
      hash = (37 * hash) + PREFABPATH_FIELD_NUMBER;
      hash = (53 * hash) + getPrefabPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDescAll.ConfigDesc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigDescAll.ConfigDesc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigDesc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigDesc)
        com.inke.conf.ConfigDescAll.ConfigDescOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigDescAll.internal_static_ConfigDesc_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigDescAll.internal_static_ConfigDesc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigDescAll.ConfigDesc.class, com.inke.conf.ConfigDescAll.ConfigDesc.Builder.class);
      }

      // Construct using com.inke.conf.ConfigDescAll.ConfigDesc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        desc_ = "";

        name_ = "";

        iconPath_ = "";

        prefabPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigDescAll.internal_static_ConfigDesc_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDescAll.ConfigDesc getDefaultInstanceForType() {
        return com.inke.conf.ConfigDescAll.ConfigDesc.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigDescAll.ConfigDesc build() {
        com.inke.conf.ConfigDescAll.ConfigDesc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDescAll.ConfigDesc buildPartial() {
        com.inke.conf.ConfigDescAll.ConfigDesc result = new com.inke.conf.ConfigDescAll.ConfigDesc(this);
        result.id_ = id_;
        result.desc_ = desc_;
        result.name_ = name_;
        result.iconPath_ = iconPath_;
        result.prefabPath_ = prefabPath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigDescAll.ConfigDesc) {
          return mergeFrom((com.inke.conf.ConfigDescAll.ConfigDesc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigDescAll.ConfigDesc other) {
        if (other == com.inke.conf.ConfigDescAll.ConfigDesc.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getIconPath().isEmpty()) {
          iconPath_ = other.iconPath_;
          onChanged();
        }
        if (!other.getPrefabPath().isEmpty()) {
          prefabPath_ = other.prefabPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigDescAll.ConfigDesc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigDescAll.ConfigDesc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 2;</code>
       * @return The desc.
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iconPath_ = "";
      /**
       * <code>string iconPath = 4;</code>
       * @return The iconPath.
       */
      public java.lang.String getIconPath() {
        java.lang.Object ref = iconPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iconPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string iconPath = 4;</code>
       * @return The bytes for iconPath.
       */
      public com.google.protobuf.ByteString
          getIconPathBytes() {
        java.lang.Object ref = iconPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string iconPath = 4;</code>
       * @param value The iconPath to set.
       * @return This builder for chaining.
       */
      public Builder setIconPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iconPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string iconPath = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIconPath() {
        
        iconPath_ = getDefaultInstance().getIconPath();
        onChanged();
        return this;
      }
      /**
       * <code>string iconPath = 4;</code>
       * @param value The bytes for iconPath to set.
       * @return This builder for chaining.
       */
      public Builder setIconPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iconPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object prefabPath_ = "";
      /**
       * <code>string prefabPath = 5;</code>
       * @return The prefabPath.
       */
      public java.lang.String getPrefabPath() {
        java.lang.Object ref = prefabPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prefabPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string prefabPath = 5;</code>
       * @return The bytes for prefabPath.
       */
      public com.google.protobuf.ByteString
          getPrefabPathBytes() {
        java.lang.Object ref = prefabPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prefabPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prefabPath = 5;</code>
       * @param value The prefabPath to set.
       * @return This builder for chaining.
       */
      public Builder setPrefabPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prefabPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string prefabPath = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrefabPath() {
        
        prefabPath_ = getDefaultInstance().getPrefabPath();
        onChanged();
        return this;
      }
      /**
       * <code>string prefabPath = 5;</code>
       * @param value The bytes for prefabPath to set.
       * @return This builder for chaining.
       */
      public Builder setPrefabPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        prefabPath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigDesc)
    }

    // @@protoc_insertion_point(class_scope:ConfigDesc)
    private static final com.inke.conf.ConfigDescAll.ConfigDesc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigDescAll.ConfigDesc();
    }

    public static com.inke.conf.ConfigDescAll.ConfigDesc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigDesc>
        PARSER = new com.google.protobuf.AbstractParser<ConfigDesc>() {
      @java.lang.Override
      public ConfigDesc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigDesc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigDesc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigDesc> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigDescAll.ConfigDesc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigDescList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigDescList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigDesc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigDesc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ConfigDesc.proto\"+\n\016ConfigDescList\022\031\n\004" +
      "list\030\001 \003(\0132\013.ConfigDesc\"Z\n\nConfigDesc\022\n\n" +
      "\002id\030\001 \001(\005\022\014\n\004desc\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\020\n" +
      "\010iconPath\030\004 \001(\t\022\022\n\nprefabPath\030\005 \001(\tB&\n\rc" +
      "om.inke.confB\rConfigDescAllZ\006.;gameb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConfigDescList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigDescList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigDescList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ConfigDesc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigDesc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigDesc_descriptor,
        new java.lang.String[] { "Id", "Desc", "Name", "IconPath", "PrefabPath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
