// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigBuff.proto

package com.inke.conf;

public final class ConfigBuffAll {
  private ConfigBuffAll() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigBuffListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigBuffList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    java.util.List<com.inke.conf.ConfigBuffAll.ConfigBuff> 
        getListList();
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    com.inke.conf.ConfigBuffAll.ConfigBuff getList(int index);
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    java.util.List<? extends com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigBuffList}
   */
  public static final class ConfigBuffList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigBuffList)
      ConfigBuffListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigBuffList.newBuilder() to construct.
    private ConfigBuffList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigBuffList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigBuffList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigBuffList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.inke.conf.ConfigBuffAll.ConfigBuff>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.inke.conf.ConfigBuffAll.ConfigBuff.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuffList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuffList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigBuffAll.ConfigBuffList.class, com.inke.conf.ConfigBuffAll.ConfigBuffList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.inke.conf.ConfigBuffAll.ConfigBuff> list_;
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.inke.conf.ConfigBuffAll.ConfigBuff> getListList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigBuffAll.ConfigBuff getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .ConfigBuff list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigBuffAll.ConfigBuffList)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigBuffAll.ConfigBuffList other = (com.inke.conf.ConfigBuffAll.ConfigBuffList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuffList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigBuffAll.ConfigBuffList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigBuffList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigBuffList)
        com.inke.conf.ConfigBuffAll.ConfigBuffListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuffList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuffList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigBuffAll.ConfigBuffList.class, com.inke.conf.ConfigBuffAll.ConfigBuffList.Builder.class);
      }

      // Construct using com.inke.conf.ConfigBuffAll.ConfigBuffList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuffList_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuffAll.ConfigBuffList getDefaultInstanceForType() {
        return com.inke.conf.ConfigBuffAll.ConfigBuffList.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuffAll.ConfigBuffList build() {
        com.inke.conf.ConfigBuffAll.ConfigBuffList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuffAll.ConfigBuffList buildPartial() {
        com.inke.conf.ConfigBuffAll.ConfigBuffList result = new com.inke.conf.ConfigBuffAll.ConfigBuffList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigBuffAll.ConfigBuffList) {
          return mergeFrom((com.inke.conf.ConfigBuffAll.ConfigBuffList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigBuffAll.ConfigBuffList other) {
        if (other == com.inke.conf.ConfigBuffAll.ConfigBuffList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigBuffAll.ConfigBuffList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigBuffAll.ConfigBuffList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.inke.conf.ConfigBuffAll.ConfigBuff> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.inke.conf.ConfigBuffAll.ConfigBuff>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigBuffAll.ConfigBuff, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder, com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder> listBuilder_;

      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigBuffAll.ConfigBuff> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public com.inke.conf.ConfigBuffAll.ConfigBuff getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigBuffAll.ConfigBuff value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder addList(com.inke.conf.ConfigBuffAll.ConfigBuff value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigBuffAll.ConfigBuff value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder addList(
          com.inke.conf.ConfigBuffAll.ConfigBuff.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.inke.conf.ConfigBuffAll.ConfigBuff> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public com.inke.conf.ConfigBuffAll.ConfigBuff.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public java.util.List<? extends com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public com.inke.conf.ConfigBuffAll.ConfigBuff.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.inke.conf.ConfigBuffAll.ConfigBuff.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public com.inke.conf.ConfigBuffAll.ConfigBuff.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.inke.conf.ConfigBuffAll.ConfigBuff.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigBuff list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigBuffAll.ConfigBuff.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigBuffAll.ConfigBuff, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder, com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.inke.conf.ConfigBuffAll.ConfigBuff, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder, com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigBuffList)
    }

    // @@protoc_insertion_point(class_scope:ConfigBuffList)
    private static final com.inke.conf.ConfigBuffAll.ConfigBuffList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigBuffAll.ConfigBuffList();
    }

    public static com.inke.conf.ConfigBuffAll.ConfigBuffList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigBuffList>
        PARSER = new com.google.protobuf.AbstractParser<ConfigBuffList>() {
      @java.lang.Override
      public ConfigBuffList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigBuffList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigBuffList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigBuffList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigBuffAll.ConfigBuffList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigBuffOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigBuff)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 typeId = 1;</code>
     * @return The typeId.
     */
    int getTypeId();

    /**
     * <code>int32 targetId = 2;</code>
     * @return The targetId.
     */
    int getTargetId();

    /**
     * <code>int32 goldGainRate = 3;</code>
     * @return The goldGainRate.
     */
    int getGoldGainRate();

    /**
     * <code>int32 cooldownRate = 4;</code>
     * @return The cooldownRate.
     */
    int getCooldownRate();

    /**
     * <code>int32 buildingShockRate = 5;</code>
     * @return The buildingShockRate.
     */
    int getBuildingShockRate();

    /**
     * <code>int32 monsterShockRate = 6;</code>
     * @return The monsterShockRate.
     */
    int getMonsterShockRate();

    /**
     * <code>int32 touristAmountRate = 7;</code>
     * @return The touristAmountRate.
     */
    int getTouristAmountRate();
  }
  /**
   * Protobuf type {@code ConfigBuff}
   */
  public static final class ConfigBuff extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigBuff)
      ConfigBuffOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigBuff.newBuilder() to construct.
    private ConfigBuff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigBuff() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigBuff();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigBuff(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              typeId_ = input.readInt32();
              break;
            }
            case 16: {

              targetId_ = input.readInt32();
              break;
            }
            case 24: {

              goldGainRate_ = input.readInt32();
              break;
            }
            case 32: {

              cooldownRate_ = input.readInt32();
              break;
            }
            case 40: {

              buildingShockRate_ = input.readInt32();
              break;
            }
            case 48: {

              monsterShockRate_ = input.readInt32();
              break;
            }
            case 56: {

              touristAmountRate_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuff_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigBuffAll.ConfigBuff.class, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder.class);
    }

    public static final int TYPEID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <code>int32 typeId = 1;</code>
     * @return The typeId.
     */
    @java.lang.Override
    public int getTypeId() {
      return typeId_;
    }

    public static final int TARGETID_FIELD_NUMBER = 2;
    private int targetId_;
    /**
     * <code>int32 targetId = 2;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public int getTargetId() {
      return targetId_;
    }

    public static final int GOLDGAINRATE_FIELD_NUMBER = 3;
    private int goldGainRate_;
    /**
     * <code>int32 goldGainRate = 3;</code>
     * @return The goldGainRate.
     */
    @java.lang.Override
    public int getGoldGainRate() {
      return goldGainRate_;
    }

    public static final int COOLDOWNRATE_FIELD_NUMBER = 4;
    private int cooldownRate_;
    /**
     * <code>int32 cooldownRate = 4;</code>
     * @return The cooldownRate.
     */
    @java.lang.Override
    public int getCooldownRate() {
      return cooldownRate_;
    }

    public static final int BUILDINGSHOCKRATE_FIELD_NUMBER = 5;
    private int buildingShockRate_;
    /**
     * <code>int32 buildingShockRate = 5;</code>
     * @return The buildingShockRate.
     */
    @java.lang.Override
    public int getBuildingShockRate() {
      return buildingShockRate_;
    }

    public static final int MONSTERSHOCKRATE_FIELD_NUMBER = 6;
    private int monsterShockRate_;
    /**
     * <code>int32 monsterShockRate = 6;</code>
     * @return The monsterShockRate.
     */
    @java.lang.Override
    public int getMonsterShockRate() {
      return monsterShockRate_;
    }

    public static final int TOURISTAMOUNTRATE_FIELD_NUMBER = 7;
    private int touristAmountRate_;
    /**
     * <code>int32 touristAmountRate = 7;</code>
     * @return The touristAmountRate.
     */
    @java.lang.Override
    public int getTouristAmountRate() {
      return touristAmountRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeId_ != 0) {
        output.writeInt32(1, typeId_);
      }
      if (targetId_ != 0) {
        output.writeInt32(2, targetId_);
      }
      if (goldGainRate_ != 0) {
        output.writeInt32(3, goldGainRate_);
      }
      if (cooldownRate_ != 0) {
        output.writeInt32(4, cooldownRate_);
      }
      if (buildingShockRate_ != 0) {
        output.writeInt32(5, buildingShockRate_);
      }
      if (monsterShockRate_ != 0) {
        output.writeInt32(6, monsterShockRate_);
      }
      if (touristAmountRate_ != 0) {
        output.writeInt32(7, touristAmountRate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, typeId_);
      }
      if (targetId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, targetId_);
      }
      if (goldGainRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goldGainRate_);
      }
      if (cooldownRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cooldownRate_);
      }
      if (buildingShockRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, buildingShockRate_);
      }
      if (monsterShockRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, monsterShockRate_);
      }
      if (touristAmountRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, touristAmountRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigBuffAll.ConfigBuff)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigBuffAll.ConfigBuff other = (com.inke.conf.ConfigBuffAll.ConfigBuff) obj;

      if (getTypeId()
          != other.getTypeId()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (getGoldGainRate()
          != other.getGoldGainRate()) return false;
      if (getCooldownRate()
          != other.getCooldownRate()) return false;
      if (getBuildingShockRate()
          != other.getBuildingShockRate()) return false;
      if (getMonsterShockRate()
          != other.getMonsterShockRate()) return false;
      if (getTouristAmountRate()
          != other.getTouristAmountRate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId();
      hash = (37 * hash) + GOLDGAINRATE_FIELD_NUMBER;
      hash = (53 * hash) + getGoldGainRate();
      hash = (37 * hash) + COOLDOWNRATE_FIELD_NUMBER;
      hash = (53 * hash) + getCooldownRate();
      hash = (37 * hash) + BUILDINGSHOCKRATE_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingShockRate();
      hash = (37 * hash) + MONSTERSHOCKRATE_FIELD_NUMBER;
      hash = (53 * hash) + getMonsterShockRate();
      hash = (37 * hash) + TOURISTAMOUNTRATE_FIELD_NUMBER;
      hash = (53 * hash) + getTouristAmountRate();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigBuffAll.ConfigBuff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigBuffAll.ConfigBuff prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigBuff}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigBuff)
        com.inke.conf.ConfigBuffAll.ConfigBuffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuff_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigBuffAll.ConfigBuff.class, com.inke.conf.ConfigBuffAll.ConfigBuff.Builder.class);
      }

      // Construct using com.inke.conf.ConfigBuffAll.ConfigBuff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeId_ = 0;

        targetId_ = 0;

        goldGainRate_ = 0;

        cooldownRate_ = 0;

        buildingShockRate_ = 0;

        monsterShockRate_ = 0;

        touristAmountRate_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigBuffAll.internal_static_ConfigBuff_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuffAll.ConfigBuff getDefaultInstanceForType() {
        return com.inke.conf.ConfigBuffAll.ConfigBuff.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuffAll.ConfigBuff build() {
        com.inke.conf.ConfigBuffAll.ConfigBuff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigBuffAll.ConfigBuff buildPartial() {
        com.inke.conf.ConfigBuffAll.ConfigBuff result = new com.inke.conf.ConfigBuffAll.ConfigBuff(this);
        result.typeId_ = typeId_;
        result.targetId_ = targetId_;
        result.goldGainRate_ = goldGainRate_;
        result.cooldownRate_ = cooldownRate_;
        result.buildingShockRate_ = buildingShockRate_;
        result.monsterShockRate_ = monsterShockRate_;
        result.touristAmountRate_ = touristAmountRate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigBuffAll.ConfigBuff) {
          return mergeFrom((com.inke.conf.ConfigBuffAll.ConfigBuff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigBuffAll.ConfigBuff other) {
        if (other == com.inke.conf.ConfigBuffAll.ConfigBuff.getDefaultInstance()) return this;
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (other.getTargetId() != 0) {
          setTargetId(other.getTargetId());
        }
        if (other.getGoldGainRate() != 0) {
          setGoldGainRate(other.getGoldGainRate());
        }
        if (other.getCooldownRate() != 0) {
          setCooldownRate(other.getCooldownRate());
        }
        if (other.getBuildingShockRate() != 0) {
          setBuildingShockRate(other.getBuildingShockRate());
        }
        if (other.getMonsterShockRate() != 0) {
          setMonsterShockRate(other.getMonsterShockRate());
        }
        if (other.getTouristAmountRate() != 0) {
          setTouristAmountRate(other.getTouristAmountRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigBuffAll.ConfigBuff parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigBuffAll.ConfigBuff) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int typeId_ ;
      /**
       * <code>int32 typeId = 1;</code>
       * @return The typeId.
       */
      @java.lang.Override
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>int32 typeId = 1;</code>
       * @param value The typeId to set.
       * @return This builder for chaining.
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private int targetId_ ;
      /**
       * <code>int32 targetId = 2;</code>
       * @return The targetId.
       */
      @java.lang.Override
      public int getTargetId() {
        return targetId_;
      }
      /**
       * <code>int32 targetId = 2;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(int value) {
        
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 targetId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        
        targetId_ = 0;
        onChanged();
        return this;
      }

      private int goldGainRate_ ;
      /**
       * <code>int32 goldGainRate = 3;</code>
       * @return The goldGainRate.
       */
      @java.lang.Override
      public int getGoldGainRate() {
        return goldGainRate_;
      }
      /**
       * <code>int32 goldGainRate = 3;</code>
       * @param value The goldGainRate to set.
       * @return This builder for chaining.
       */
      public Builder setGoldGainRate(int value) {
        
        goldGainRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 goldGainRate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGoldGainRate() {
        
        goldGainRate_ = 0;
        onChanged();
        return this;
      }

      private int cooldownRate_ ;
      /**
       * <code>int32 cooldownRate = 4;</code>
       * @return The cooldownRate.
       */
      @java.lang.Override
      public int getCooldownRate() {
        return cooldownRate_;
      }
      /**
       * <code>int32 cooldownRate = 4;</code>
       * @param value The cooldownRate to set.
       * @return This builder for chaining.
       */
      public Builder setCooldownRate(int value) {
        
        cooldownRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cooldownRate = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCooldownRate() {
        
        cooldownRate_ = 0;
        onChanged();
        return this;
      }

      private int buildingShockRate_ ;
      /**
       * <code>int32 buildingShockRate = 5;</code>
       * @return The buildingShockRate.
       */
      @java.lang.Override
      public int getBuildingShockRate() {
        return buildingShockRate_;
      }
      /**
       * <code>int32 buildingShockRate = 5;</code>
       * @param value The buildingShockRate to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingShockRate(int value) {
        
        buildingShockRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buildingShockRate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingShockRate() {
        
        buildingShockRate_ = 0;
        onChanged();
        return this;
      }

      private int monsterShockRate_ ;
      /**
       * <code>int32 monsterShockRate = 6;</code>
       * @return The monsterShockRate.
       */
      @java.lang.Override
      public int getMonsterShockRate() {
        return monsterShockRate_;
      }
      /**
       * <code>int32 monsterShockRate = 6;</code>
       * @param value The monsterShockRate to set.
       * @return This builder for chaining.
       */
      public Builder setMonsterShockRate(int value) {
        
        monsterShockRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 monsterShockRate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonsterShockRate() {
        
        monsterShockRate_ = 0;
        onChanged();
        return this;
      }

      private int touristAmountRate_ ;
      /**
       * <code>int32 touristAmountRate = 7;</code>
       * @return The touristAmountRate.
       */
      @java.lang.Override
      public int getTouristAmountRate() {
        return touristAmountRate_;
      }
      /**
       * <code>int32 touristAmountRate = 7;</code>
       * @param value The touristAmountRate to set.
       * @return This builder for chaining.
       */
      public Builder setTouristAmountRate(int value) {
        
        touristAmountRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 touristAmountRate = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTouristAmountRate() {
        
        touristAmountRate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigBuff)
    }

    // @@protoc_insertion_point(class_scope:ConfigBuff)
    private static final com.inke.conf.ConfigBuffAll.ConfigBuff DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigBuffAll.ConfigBuff();
    }

    public static com.inke.conf.ConfigBuffAll.ConfigBuff getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigBuff>
        PARSER = new com.google.protobuf.AbstractParser<ConfigBuff>() {
      @java.lang.Override
      public ConfigBuff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigBuff(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigBuff> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigBuff> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigBuffAll.ConfigBuff getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigBuffList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigBuffList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigBuff_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigBuff_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ConfigBuff.proto\"+\n\016ConfigBuffList\022\031\n\004" +
      "list\030\001 \003(\0132\013.ConfigBuff\"\252\001\n\nConfigBuff\022\016" +
      "\n\006typeId\030\001 \001(\005\022\020\n\010targetId\030\002 \001(\005\022\024\n\014gold" +
      "GainRate\030\003 \001(\005\022\024\n\014cooldownRate\030\004 \001(\005\022\031\n\021" +
      "buildingShockRate\030\005 \001(\005\022\030\n\020monsterShockR" +
      "ate\030\006 \001(\005\022\031\n\021touristAmountRate\030\007 \001(\005B&\n\r" +
      "com.inke.confB\rConfigBuffAllZ\006.;gameb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConfigBuffList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigBuffList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigBuffList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ConfigBuff_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigBuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigBuff_descriptor,
        new java.lang.String[] { "TypeId", "TargetId", "GoldGainRate", "CooldownRate", "BuildingShockRate", "MonsterShockRate", "TouristAmountRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
