// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigDecoration.proto

package com.inke.conf;

public final class ConfigDecorationAll {
  private ConfigDecorationAll() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigDecorationListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigDecorationList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    java.util.List<com.inke.conf.ConfigDecorationAll.ConfigDecoration> 
        getListList();
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    com.inke.conf.ConfigDecorationAll.ConfigDecoration getList(int index);
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    java.util.List<? extends com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigDecorationList}
   */
  public static final class ConfigDecorationList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigDecorationList)
      ConfigDecorationListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigDecorationList.newBuilder() to construct.
    private ConfigDecorationList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigDecorationList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigDecorationList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigDecorationList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.inke.conf.ConfigDecorationAll.ConfigDecoration>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.inke.conf.ConfigDecorationAll.ConfigDecoration.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecorationList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecorationList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigDecorationAll.ConfigDecorationList.class, com.inke.conf.ConfigDecorationAll.ConfigDecorationList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.inke.conf.ConfigDecorationAll.ConfigDecoration> list_;
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.inke.conf.ConfigDecorationAll.ConfigDecoration> getListList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigDecorationAll.ConfigDecoration getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .ConfigDecoration list = 1;</code>
     */
    @java.lang.Override
    public com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigDecorationAll.ConfigDecorationList)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigDecorationAll.ConfigDecorationList other = (com.inke.conf.ConfigDecorationAll.ConfigDecorationList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigDecorationAll.ConfigDecorationList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigDecorationList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigDecorationList)
        com.inke.conf.ConfigDecorationAll.ConfigDecorationListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecorationList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecorationList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigDecorationAll.ConfigDecorationList.class, com.inke.conf.ConfigDecorationAll.ConfigDecorationList.Builder.class);
      }

      // Construct using com.inke.conf.ConfigDecorationAll.ConfigDecorationList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecorationList_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDecorationAll.ConfigDecorationList getDefaultInstanceForType() {
        return com.inke.conf.ConfigDecorationAll.ConfigDecorationList.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigDecorationAll.ConfigDecorationList build() {
        com.inke.conf.ConfigDecorationAll.ConfigDecorationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDecorationAll.ConfigDecorationList buildPartial() {
        com.inke.conf.ConfigDecorationAll.ConfigDecorationList result = new com.inke.conf.ConfigDecorationAll.ConfigDecorationList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigDecorationAll.ConfigDecorationList) {
          return mergeFrom((com.inke.conf.ConfigDecorationAll.ConfigDecorationList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigDecorationAll.ConfigDecorationList other) {
        if (other == com.inke.conf.ConfigDecorationAll.ConfigDecorationList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigDecorationAll.ConfigDecorationList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigDecorationAll.ConfigDecorationList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.inke.conf.ConfigDecorationAll.ConfigDecoration> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.inke.conf.ConfigDecorationAll.ConfigDecoration>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigDecorationAll.ConfigDecoration, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder, com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder> listBuilder_;

      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigDecorationAll.ConfigDecoration> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigDecorationAll.ConfigDecoration value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder setList(
          int index, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder addList(com.inke.conf.ConfigDecorationAll.ConfigDecoration value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigDecorationAll.ConfigDecoration value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder addList(
          com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder addList(
          int index, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.inke.conf.ConfigDecorationAll.ConfigDecoration> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public java.util.List<? extends com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.inke.conf.ConfigDecorationAll.ConfigDecoration.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.inke.conf.ConfigDecorationAll.ConfigDecoration.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigDecoration list = 1;</code>
       */
      public java.util.List<com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.inke.conf.ConfigDecorationAll.ConfigDecoration, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder, com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.inke.conf.ConfigDecorationAll.ConfigDecoration, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder, com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigDecorationList)
    }

    // @@protoc_insertion_point(class_scope:ConfigDecorationList)
    private static final com.inke.conf.ConfigDecorationAll.ConfigDecorationList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigDecorationAll.ConfigDecorationList();
    }

    public static com.inke.conf.ConfigDecorationAll.ConfigDecorationList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigDecorationList>
        PARSER = new com.google.protobuf.AbstractParser<ConfigDecorationList>() {
      @java.lang.Override
      public ConfigDecorationList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigDecorationList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigDecorationList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigDecorationList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigDecorationAll.ConfigDecorationList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigDecorationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigDecoration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 typeId = 1;</code>
     * @return The typeId.
     */
    int getTypeId();

    /**
     * <code>int32 buffId = 2;</code>
     * @return The buffId.
     */
    int getBuffId();

    /**
     * <code>int32 priceId = 3;</code>
     * @return The priceId.
     */
    int getPriceId();

    /**
     * <code>int32 descId = 4;</code>
     * @return The descId.
     */
    int getDescId();

    /**
     * <code>int32 miniMapId = 5;</code>
     * @return The miniMapId.
     */
    int getMiniMapId();
  }
  /**
   * Protobuf type {@code ConfigDecoration}
   */
  public static final class ConfigDecoration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigDecoration)
      ConfigDecorationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigDecoration.newBuilder() to construct.
    private ConfigDecoration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigDecoration() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigDecoration();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigDecoration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              typeId_ = input.readInt32();
              break;
            }
            case 16: {

              buffId_ = input.readInt32();
              break;
            }
            case 24: {

              priceId_ = input.readInt32();
              break;
            }
            case 32: {

              descId_ = input.readInt32();
              break;
            }
            case 40: {

              miniMapId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecoration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecoration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inke.conf.ConfigDecorationAll.ConfigDecoration.class, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder.class);
    }

    public static final int TYPEID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <code>int32 typeId = 1;</code>
     * @return The typeId.
     */
    @java.lang.Override
    public int getTypeId() {
      return typeId_;
    }

    public static final int BUFFID_FIELD_NUMBER = 2;
    private int buffId_;
    /**
     * <code>int32 buffId = 2;</code>
     * @return The buffId.
     */
    @java.lang.Override
    public int getBuffId() {
      return buffId_;
    }

    public static final int PRICEID_FIELD_NUMBER = 3;
    private int priceId_;
    /**
     * <code>int32 priceId = 3;</code>
     * @return The priceId.
     */
    @java.lang.Override
    public int getPriceId() {
      return priceId_;
    }

    public static final int DESCID_FIELD_NUMBER = 4;
    private int descId_;
    /**
     * <code>int32 descId = 4;</code>
     * @return The descId.
     */
    @java.lang.Override
    public int getDescId() {
      return descId_;
    }

    public static final int MINIMAPID_FIELD_NUMBER = 5;
    private int miniMapId_;
    /**
     * <code>int32 miniMapId = 5;</code>
     * @return The miniMapId.
     */
    @java.lang.Override
    public int getMiniMapId() {
      return miniMapId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeId_ != 0) {
        output.writeInt32(1, typeId_);
      }
      if (buffId_ != 0) {
        output.writeInt32(2, buffId_);
      }
      if (priceId_ != 0) {
        output.writeInt32(3, priceId_);
      }
      if (descId_ != 0) {
        output.writeInt32(4, descId_);
      }
      if (miniMapId_ != 0) {
        output.writeInt32(5, miniMapId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, typeId_);
      }
      if (buffId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buffId_);
      }
      if (priceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, priceId_);
      }
      if (descId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, descId_);
      }
      if (miniMapId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, miniMapId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.inke.conf.ConfigDecorationAll.ConfigDecoration)) {
        return super.equals(obj);
      }
      com.inke.conf.ConfigDecorationAll.ConfigDecoration other = (com.inke.conf.ConfigDecorationAll.ConfigDecoration) obj;

      if (getTypeId()
          != other.getTypeId()) return false;
      if (getBuffId()
          != other.getBuffId()) return false;
      if (getPriceId()
          != other.getPriceId()) return false;
      if (getDescId()
          != other.getDescId()) return false;
      if (getMiniMapId()
          != other.getMiniMapId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (37 * hash) + BUFFID_FIELD_NUMBER;
      hash = (53 * hash) + getBuffId();
      hash = (37 * hash) + PRICEID_FIELD_NUMBER;
      hash = (53 * hash) + getPriceId();
      hash = (37 * hash) + DESCID_FIELD_NUMBER;
      hash = (53 * hash) + getDescId();
      hash = (37 * hash) + MINIMAPID_FIELD_NUMBER;
      hash = (53 * hash) + getMiniMapId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.inke.conf.ConfigDecorationAll.ConfigDecoration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigDecoration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigDecoration)
        com.inke.conf.ConfigDecorationAll.ConfigDecorationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecoration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecoration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inke.conf.ConfigDecorationAll.ConfigDecoration.class, com.inke.conf.ConfigDecorationAll.ConfigDecoration.Builder.class);
      }

      // Construct using com.inke.conf.ConfigDecorationAll.ConfigDecoration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeId_ = 0;

        buffId_ = 0;

        priceId_ = 0;

        descId_ = 0;

        miniMapId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inke.conf.ConfigDecorationAll.internal_static_ConfigDecoration_descriptor;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration getDefaultInstanceForType() {
        return com.inke.conf.ConfigDecorationAll.ConfigDecoration.getDefaultInstance();
      }

      @java.lang.Override
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration build() {
        com.inke.conf.ConfigDecorationAll.ConfigDecoration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.inke.conf.ConfigDecorationAll.ConfigDecoration buildPartial() {
        com.inke.conf.ConfigDecorationAll.ConfigDecoration result = new com.inke.conf.ConfigDecorationAll.ConfigDecoration(this);
        result.typeId_ = typeId_;
        result.buffId_ = buffId_;
        result.priceId_ = priceId_;
        result.descId_ = descId_;
        result.miniMapId_ = miniMapId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inke.conf.ConfigDecorationAll.ConfigDecoration) {
          return mergeFrom((com.inke.conf.ConfigDecorationAll.ConfigDecoration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inke.conf.ConfigDecorationAll.ConfigDecoration other) {
        if (other == com.inke.conf.ConfigDecorationAll.ConfigDecoration.getDefaultInstance()) return this;
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (other.getBuffId() != 0) {
          setBuffId(other.getBuffId());
        }
        if (other.getPriceId() != 0) {
          setPriceId(other.getPriceId());
        }
        if (other.getDescId() != 0) {
          setDescId(other.getDescId());
        }
        if (other.getMiniMapId() != 0) {
          setMiniMapId(other.getMiniMapId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inke.conf.ConfigDecorationAll.ConfigDecoration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inke.conf.ConfigDecorationAll.ConfigDecoration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int typeId_ ;
      /**
       * <code>int32 typeId = 1;</code>
       * @return The typeId.
       */
      @java.lang.Override
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>int32 typeId = 1;</code>
       * @param value The typeId to set.
       * @return This builder for chaining.
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private int buffId_ ;
      /**
       * <code>int32 buffId = 2;</code>
       * @return The buffId.
       */
      @java.lang.Override
      public int getBuffId() {
        return buffId_;
      }
      /**
       * <code>int32 buffId = 2;</code>
       * @param value The buffId to set.
       * @return This builder for chaining.
       */
      public Builder setBuffId(int value) {
        
        buffId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buffId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuffId() {
        
        buffId_ = 0;
        onChanged();
        return this;
      }

      private int priceId_ ;
      /**
       * <code>int32 priceId = 3;</code>
       * @return The priceId.
       */
      @java.lang.Override
      public int getPriceId() {
        return priceId_;
      }
      /**
       * <code>int32 priceId = 3;</code>
       * @param value The priceId to set.
       * @return This builder for chaining.
       */
      public Builder setPriceId(int value) {
        
        priceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 priceId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceId() {
        
        priceId_ = 0;
        onChanged();
        return this;
      }

      private int descId_ ;
      /**
       * <code>int32 descId = 4;</code>
       * @return The descId.
       */
      @java.lang.Override
      public int getDescId() {
        return descId_;
      }
      /**
       * <code>int32 descId = 4;</code>
       * @param value The descId to set.
       * @return This builder for chaining.
       */
      public Builder setDescId(int value) {
        
        descId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 descId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescId() {
        
        descId_ = 0;
        onChanged();
        return this;
      }

      private int miniMapId_ ;
      /**
       * <code>int32 miniMapId = 5;</code>
       * @return The miniMapId.
       */
      @java.lang.Override
      public int getMiniMapId() {
        return miniMapId_;
      }
      /**
       * <code>int32 miniMapId = 5;</code>
       * @param value The miniMapId to set.
       * @return This builder for chaining.
       */
      public Builder setMiniMapId(int value) {
        
        miniMapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 miniMapId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMiniMapId() {
        
        miniMapId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigDecoration)
    }

    // @@protoc_insertion_point(class_scope:ConfigDecoration)
    private static final com.inke.conf.ConfigDecorationAll.ConfigDecoration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.inke.conf.ConfigDecorationAll.ConfigDecoration();
    }

    public static com.inke.conf.ConfigDecorationAll.ConfigDecoration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigDecoration>
        PARSER = new com.google.protobuf.AbstractParser<ConfigDecoration>() {
      @java.lang.Override
      public ConfigDecoration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigDecoration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigDecoration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigDecoration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.inke.conf.ConfigDecorationAll.ConfigDecoration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigDecorationList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigDecorationList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigDecoration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigDecoration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ConfigDecoration.proto\"7\n\024ConfigDecora" +
      "tionList\022\037\n\004list\030\001 \003(\0132\021.ConfigDecoratio" +
      "n\"f\n\020ConfigDecoration\022\016\n\006typeId\030\001 \001(\005\022\016\n" +
      "\006buffId\030\002 \001(\005\022\017\n\007priceId\030\003 \001(\005\022\016\n\006descId" +
      "\030\004 \001(\005\022\021\n\tminiMapId\030\005 \001(\005B,\n\rcom.inke.co" +
      "nfB\023ConfigDecorationAllZ\006.;gameb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConfigDecorationList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigDecorationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigDecorationList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ConfigDecoration_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigDecoration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigDecoration_descriptor,
        new java.lang.String[] { "TypeId", "BuffId", "PriceId", "DescId", "MiniMapId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
